// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlogArticleTag = "blog_article_tag"

// BlogArticleTag 文章标签关联
type BlogArticleTag struct {
	ID         uint32  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ArticleID  int32   `gorm:"column:article_id;type:int;not null;comment:文章 ID" json:"article_id"`          // 文章 ID
	TagID      uint32  `gorm:"column:tag_id;type:int unsigned;not null;comment:标签 ID" json:"tag_id"`         // 标签 ID
	CreatedOn  *uint32 `gorm:"column:created_on;type:int unsigned;comment:创建时间" json:"created_on"`           // 创建时间
	CreatedBy  *string `gorm:"column:created_by;type:varchar(100);comment:创建人" json:"created_by"`            // 创建人
	ModifiedOn *uint32 `gorm:"column:modified_on;type:int unsigned;comment:修改时间" json:"modified_on"`         // 修改时间
	ModifiedBy *string `gorm:"column:modified_by;type:varchar(100);comment:修改人" json:"modified_by"`          // 修改人
	DeletedOn  *uint32 `gorm:"column:deleted_on;type:int unsigned;comment:删除时间" json:"deleted_on"`           // 删除时间
	IsDel      *uint32 `gorm:"column:is_del;type:tinyint unsigned;comment:是否删除 0 为未删除、1 为已删除" json:"is_del"` // 是否删除 0 为未删除、1 为已删除
}

// TableName BlogArticleTag's table name
func (*BlogArticleTag) TableName() string {
	return TableNameBlogArticleTag
}
