// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlogTag = "blog_tag"

// BlogTag 标签管理
type BlogTag struct {
	ID         uint32  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name       *string `gorm:"column:name;type:varchar(100);comment:标签名称" json:"name"`                           // 标签名称
	CreatedOn  *uint32 `gorm:"column:created_on;type:int unsigned;comment:创建时间" json:"created_on"`               // 创建时间
	CreatedBy  *string `gorm:"column:created_by;type:varchar(100);comment:创建人" json:"created_by"`                // 创建人
	ModifiedOn *uint32 `gorm:"column:modified_on;type:int unsigned;comment:修改时间" json:"modified_on"`             // 修改时间
	ModifiedBy *string `gorm:"column:modified_by;type:varchar(100);comment:修改人" json:"modified_by"`              // 修改人
	DeletedOn  *uint32 `gorm:"column:deleted_on;type:int unsigned;comment:删除时间" json:"deleted_on"`               // 删除时间
	IsDel      *uint32 `gorm:"column:is_del;type:tinyint unsigned;comment:是否删除 0 为未删除、1 为已删除" json:"is_del"`     // 是否删除 0 为未删除、1 为已删除
	State      *uint32 `gorm:"column:state;type:tinyint unsigned;default:1;comment:状态 0 为禁用、1 为启用" json:"state"` // 状态 0 为禁用、1 为启用
}

// TableName BlogTag's table name
func (*BlogTag) TableName() string {
	return TableNameBlogTag
}
