// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlogArticle = "blog_article"

// BlogArticle 文章管理
type BlogArticle struct {
	ID            uint32  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Title         *string `gorm:"column:title;type:varchar(100);comment:文章标题" json:"title"`                         // 文章标题
	Desc          *string `gorm:"column:desc;type:varchar(255);comment:文章简述" json:"desc"`                           // 文章简述
	CoverImageURL *string `gorm:"column:cover_image_url;type:varchar(255);comment:封面图片地址" json:"cover_image_url"`   // 封面图片地址
	Content       *string `gorm:"column:content;type:longtext;comment:文章内容" json:"content"`                         // 文章内容
	CreatedOn     *uint32 `gorm:"column:created_on;type:int unsigned;comment:创建时间" json:"created_on"`               // 创建时间
	CreatedBy     *string `gorm:"column:created_by;type:varchar(100);comment:创建人" json:"created_by"`                // 创建人
	ModifiedOn    *uint32 `gorm:"column:modified_on;type:int unsigned;comment:修改时间" json:"modified_on"`             // 修改时间
	ModifiedBy    *string `gorm:"column:modified_by;type:varchar(100);comment:修改人" json:"modified_by"`              // 修改人
	DeletedOn     *uint32 `gorm:"column:deleted_on;type:int unsigned;comment:删除时间" json:"deleted_on"`               // 删除时间
	IsDel         *uint32 `gorm:"column:is_del;type:tinyint unsigned;comment:是否删除 0 为未删除、1 为已删除" json:"is_del"`     // 是否删除 0 为未删除、1 为已删除
	State         *uint32 `gorm:"column:state;type:tinyint unsigned;default:1;comment:状态 0 为禁用、1 为启用" json:"state"` // 状态 0 为禁用、1 为启用
}

// TableName BlogArticle's table name
func (*BlogArticle) TableName() string {
	return TableNameBlogArticle
}
