// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/blog-service/internal/model"
)

func newBlogArticleTag(db *gorm.DB, opts ...gen.DOOption) blogArticleTag {
	_blogArticleTag := blogArticleTag{}

	_blogArticleTag.blogArticleTagDo.UseDB(db, opts...)
	_blogArticleTag.blogArticleTagDo.UseModel(&model.BlogArticleTag{})

	tableName := _blogArticleTag.blogArticleTagDo.TableName()
	_blogArticleTag.ALL = field.NewAsterisk(tableName)
	_blogArticleTag.ID = field.NewUint32(tableName, "id")
	_blogArticleTag.ArticleID = field.NewInt32(tableName, "article_id")
	_blogArticleTag.TagID = field.NewUint32(tableName, "tag_id")
	_blogArticleTag.CreatedOn = field.NewUint32(tableName, "created_on")
	_blogArticleTag.CreatedBy = field.NewString(tableName, "created_by")
	_blogArticleTag.ModifiedOn = field.NewUint32(tableName, "modified_on")
	_blogArticleTag.ModifiedBy = field.NewString(tableName, "modified_by")
	_blogArticleTag.DeletedOn = field.NewUint32(tableName, "deleted_on")
	_blogArticleTag.IsDel = field.NewUint32(tableName, "is_del")

	_blogArticleTag.fillFieldMap()

	return _blogArticleTag
}

// blogArticleTag 文章标签关联
type blogArticleTag struct {
	blogArticleTagDo blogArticleTagDo

	ALL        field.Asterisk
	ID         field.Uint32
	ArticleID  field.Int32  // 文章 ID
	TagID      field.Uint32 // 标签 ID
	CreatedOn  field.Uint32 // 创建时间
	CreatedBy  field.String // 创建人
	ModifiedOn field.Uint32 // 修改时间
	ModifiedBy field.String // 修改人
	DeletedOn  field.Uint32 // 删除时间
	IsDel      field.Uint32 // 是否删除 0 为未删除、1 为已删除

	fieldMap map[string]field.Expr
}

func (b blogArticleTag) Table(newTableName string) *blogArticleTag {
	b.blogArticleTagDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b blogArticleTag) As(alias string) *blogArticleTag {
	b.blogArticleTagDo.DO = *(b.blogArticleTagDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *blogArticleTag) updateTableName(table string) *blogArticleTag {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewUint32(table, "id")
	b.ArticleID = field.NewInt32(table, "article_id")
	b.TagID = field.NewUint32(table, "tag_id")
	b.CreatedOn = field.NewUint32(table, "created_on")
	b.CreatedBy = field.NewString(table, "created_by")
	b.ModifiedOn = field.NewUint32(table, "modified_on")
	b.ModifiedBy = field.NewString(table, "modified_by")
	b.DeletedOn = field.NewUint32(table, "deleted_on")
	b.IsDel = field.NewUint32(table, "is_del")

	b.fillFieldMap()

	return b
}

func (b *blogArticleTag) WithContext(ctx context.Context) *blogArticleTagDo {
	return b.blogArticleTagDo.WithContext(ctx)
}

func (b blogArticleTag) TableName() string { return b.blogArticleTagDo.TableName() }

func (b blogArticleTag) Alias() string { return b.blogArticleTagDo.Alias() }

func (b blogArticleTag) Columns(cols ...field.Expr) gen.Columns {
	return b.blogArticleTagDo.Columns(cols...)
}

func (b *blogArticleTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *blogArticleTag) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 9)
	b.fieldMap["id"] = b.ID
	b.fieldMap["article_id"] = b.ArticleID
	b.fieldMap["tag_id"] = b.TagID
	b.fieldMap["created_on"] = b.CreatedOn
	b.fieldMap["created_by"] = b.CreatedBy
	b.fieldMap["modified_on"] = b.ModifiedOn
	b.fieldMap["modified_by"] = b.ModifiedBy
	b.fieldMap["deleted_on"] = b.DeletedOn
	b.fieldMap["is_del"] = b.IsDel
}

func (b blogArticleTag) clone(db *gorm.DB) blogArticleTag {
	b.blogArticleTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b blogArticleTag) replaceDB(db *gorm.DB) blogArticleTag {
	b.blogArticleTagDo.ReplaceDB(db)
	return b
}

type blogArticleTagDo struct{ gen.DO }

func (b blogArticleTagDo) Debug() *blogArticleTagDo {
	return b.withDO(b.DO.Debug())
}

func (b blogArticleTagDo) WithContext(ctx context.Context) *blogArticleTagDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b blogArticleTagDo) ReadDB() *blogArticleTagDo {
	return b.Clauses(dbresolver.Read)
}

func (b blogArticleTagDo) WriteDB() *blogArticleTagDo {
	return b.Clauses(dbresolver.Write)
}

func (b blogArticleTagDo) Session(config *gorm.Session) *blogArticleTagDo {
	return b.withDO(b.DO.Session(config))
}

func (b blogArticleTagDo) Clauses(conds ...clause.Expression) *blogArticleTagDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b blogArticleTagDo) Returning(value interface{}, columns ...string) *blogArticleTagDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b blogArticleTagDo) Not(conds ...gen.Condition) *blogArticleTagDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b blogArticleTagDo) Or(conds ...gen.Condition) *blogArticleTagDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b blogArticleTagDo) Select(conds ...field.Expr) *blogArticleTagDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b blogArticleTagDo) Where(conds ...gen.Condition) *blogArticleTagDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b blogArticleTagDo) Order(conds ...field.Expr) *blogArticleTagDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b blogArticleTagDo) Distinct(cols ...field.Expr) *blogArticleTagDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b blogArticleTagDo) Omit(cols ...field.Expr) *blogArticleTagDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b blogArticleTagDo) Join(table schema.Tabler, on ...field.Expr) *blogArticleTagDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b blogArticleTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *blogArticleTagDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b blogArticleTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *blogArticleTagDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b blogArticleTagDo) Group(cols ...field.Expr) *blogArticleTagDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b blogArticleTagDo) Having(conds ...gen.Condition) *blogArticleTagDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b blogArticleTagDo) Limit(limit int) *blogArticleTagDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b blogArticleTagDo) Offset(offset int) *blogArticleTagDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b blogArticleTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *blogArticleTagDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b blogArticleTagDo) Unscoped() *blogArticleTagDo {
	return b.withDO(b.DO.Unscoped())
}

func (b blogArticleTagDo) Create(values ...*model.BlogArticleTag) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b blogArticleTagDo) CreateInBatches(values []*model.BlogArticleTag, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b blogArticleTagDo) Save(values ...*model.BlogArticleTag) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b blogArticleTagDo) First() (*model.BlogArticleTag, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticleTag), nil
	}
}

func (b blogArticleTagDo) Take() (*model.BlogArticleTag, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticleTag), nil
	}
}

func (b blogArticleTagDo) Last() (*model.BlogArticleTag, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticleTag), nil
	}
}

func (b blogArticleTagDo) Find() ([]*model.BlogArticleTag, error) {
	result, err := b.DO.Find()
	return result.([]*model.BlogArticleTag), err
}

func (b blogArticleTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BlogArticleTag, err error) {
	buf := make([]*model.BlogArticleTag, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b blogArticleTagDo) FindInBatches(result *[]*model.BlogArticleTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b blogArticleTagDo) Attrs(attrs ...field.AssignExpr) *blogArticleTagDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b blogArticleTagDo) Assign(attrs ...field.AssignExpr) *blogArticleTagDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b blogArticleTagDo) Joins(fields ...field.RelationField) *blogArticleTagDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b blogArticleTagDo) Preload(fields ...field.RelationField) *blogArticleTagDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b blogArticleTagDo) FirstOrInit() (*model.BlogArticleTag, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticleTag), nil
	}
}

func (b blogArticleTagDo) FirstOrCreate() (*model.BlogArticleTag, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticleTag), nil
	}
}

func (b blogArticleTagDo) FindByPage(offset int, limit int) (result []*model.BlogArticleTag, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b blogArticleTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b blogArticleTagDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b blogArticleTagDo) Delete(models ...*model.BlogArticleTag) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *blogArticleTagDo) withDO(do gen.Dao) *blogArticleTagDo {
	b.DO = *do.(*gen.DO)
	return b
}
