// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/blog-service/internal/model"
)

func newBlogArticle(db *gorm.DB, opts ...gen.DOOption) blogArticle {
	_blogArticle := blogArticle{}

	_blogArticle.blogArticleDo.UseDB(db, opts...)
	_blogArticle.blogArticleDo.UseModel(&model.BlogArticle{})

	tableName := _blogArticle.blogArticleDo.TableName()
	_blogArticle.ALL = field.NewAsterisk(tableName)
	_blogArticle.ID = field.NewUint32(tableName, "id")
	_blogArticle.Title = field.NewString(tableName, "title")
	_blogArticle.Desc = field.NewString(tableName, "desc")
	_blogArticle.CoverImageURL = field.NewString(tableName, "cover_image_url")
	_blogArticle.Content = field.NewString(tableName, "content")
	_blogArticle.CreatedOn = field.NewUint32(tableName, "created_on")
	_blogArticle.CreatedBy = field.NewString(tableName, "created_by")
	_blogArticle.ModifiedOn = field.NewUint32(tableName, "modified_on")
	_blogArticle.ModifiedBy = field.NewString(tableName, "modified_by")
	_blogArticle.DeletedOn = field.NewUint32(tableName, "deleted_on")
	_blogArticle.IsDel = field.NewUint32(tableName, "is_del")
	_blogArticle.State = field.NewUint32(tableName, "state")

	_blogArticle.fillFieldMap()

	return _blogArticle
}

// blogArticle 文章管理
type blogArticle struct {
	blogArticleDo blogArticleDo

	ALL           field.Asterisk
	ID            field.Uint32
	Title         field.String // 文章标题
	Desc          field.String // 文章简述
	CoverImageURL field.String // 封面图片地址
	Content       field.String // 文章内容
	CreatedOn     field.Uint32 // 创建时间
	CreatedBy     field.String // 创建人
	ModifiedOn    field.Uint32 // 修改时间
	ModifiedBy    field.String // 修改人
	DeletedOn     field.Uint32 // 删除时间
	IsDel         field.Uint32 // 是否删除 0 为未删除、1 为已删除
	State         field.Uint32 // 状态 0 为禁用、1 为启用

	fieldMap map[string]field.Expr
}

func (b blogArticle) Table(newTableName string) *blogArticle {
	b.blogArticleDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b blogArticle) As(alias string) *blogArticle {
	b.blogArticleDo.DO = *(b.blogArticleDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *blogArticle) updateTableName(table string) *blogArticle {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewUint32(table, "id")
	b.Title = field.NewString(table, "title")
	b.Desc = field.NewString(table, "desc")
	b.CoverImageURL = field.NewString(table, "cover_image_url")
	b.Content = field.NewString(table, "content")
	b.CreatedOn = field.NewUint32(table, "created_on")
	b.CreatedBy = field.NewString(table, "created_by")
	b.ModifiedOn = field.NewUint32(table, "modified_on")
	b.ModifiedBy = field.NewString(table, "modified_by")
	b.DeletedOn = field.NewUint32(table, "deleted_on")
	b.IsDel = field.NewUint32(table, "is_del")
	b.State = field.NewUint32(table, "state")

	b.fillFieldMap()

	return b
}

func (b *blogArticle) WithContext(ctx context.Context) *blogArticleDo {
	return b.blogArticleDo.WithContext(ctx)
}

func (b blogArticle) TableName() string { return b.blogArticleDo.TableName() }

func (b blogArticle) Alias() string { return b.blogArticleDo.Alias() }

func (b blogArticle) Columns(cols ...field.Expr) gen.Columns { return b.blogArticleDo.Columns(cols...) }

func (b *blogArticle) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *blogArticle) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 12)
	b.fieldMap["id"] = b.ID
	b.fieldMap["title"] = b.Title
	b.fieldMap["desc"] = b.Desc
	b.fieldMap["cover_image_url"] = b.CoverImageURL
	b.fieldMap["content"] = b.Content
	b.fieldMap["created_on"] = b.CreatedOn
	b.fieldMap["created_by"] = b.CreatedBy
	b.fieldMap["modified_on"] = b.ModifiedOn
	b.fieldMap["modified_by"] = b.ModifiedBy
	b.fieldMap["deleted_on"] = b.DeletedOn
	b.fieldMap["is_del"] = b.IsDel
	b.fieldMap["state"] = b.State
}

func (b blogArticle) clone(db *gorm.DB) blogArticle {
	b.blogArticleDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b blogArticle) replaceDB(db *gorm.DB) blogArticle {
	b.blogArticleDo.ReplaceDB(db)
	return b
}

type blogArticleDo struct{ gen.DO }

func (b blogArticleDo) Debug() *blogArticleDo {
	return b.withDO(b.DO.Debug())
}

func (b blogArticleDo) WithContext(ctx context.Context) *blogArticleDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b blogArticleDo) ReadDB() *blogArticleDo {
	return b.Clauses(dbresolver.Read)
}

func (b blogArticleDo) WriteDB() *blogArticleDo {
	return b.Clauses(dbresolver.Write)
}

func (b blogArticleDo) Session(config *gorm.Session) *blogArticleDo {
	return b.withDO(b.DO.Session(config))
}

func (b blogArticleDo) Clauses(conds ...clause.Expression) *blogArticleDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b blogArticleDo) Returning(value interface{}, columns ...string) *blogArticleDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b blogArticleDo) Not(conds ...gen.Condition) *blogArticleDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b blogArticleDo) Or(conds ...gen.Condition) *blogArticleDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b blogArticleDo) Select(conds ...field.Expr) *blogArticleDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b blogArticleDo) Where(conds ...gen.Condition) *blogArticleDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b blogArticleDo) Order(conds ...field.Expr) *blogArticleDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b blogArticleDo) Distinct(cols ...field.Expr) *blogArticleDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b blogArticleDo) Omit(cols ...field.Expr) *blogArticleDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b blogArticleDo) Join(table schema.Tabler, on ...field.Expr) *blogArticleDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b blogArticleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *blogArticleDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b blogArticleDo) RightJoin(table schema.Tabler, on ...field.Expr) *blogArticleDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b blogArticleDo) Group(cols ...field.Expr) *blogArticleDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b blogArticleDo) Having(conds ...gen.Condition) *blogArticleDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b blogArticleDo) Limit(limit int) *blogArticleDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b blogArticleDo) Offset(offset int) *blogArticleDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b blogArticleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *blogArticleDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b blogArticleDo) Unscoped() *blogArticleDo {
	return b.withDO(b.DO.Unscoped())
}

func (b blogArticleDo) Create(values ...*model.BlogArticle) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b blogArticleDo) CreateInBatches(values []*model.BlogArticle, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b blogArticleDo) Save(values ...*model.BlogArticle) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b blogArticleDo) First() (*model.BlogArticle, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticle), nil
	}
}

func (b blogArticleDo) Take() (*model.BlogArticle, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticle), nil
	}
}

func (b blogArticleDo) Last() (*model.BlogArticle, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticle), nil
	}
}

func (b blogArticleDo) Find() ([]*model.BlogArticle, error) {
	result, err := b.DO.Find()
	return result.([]*model.BlogArticle), err
}

func (b blogArticleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BlogArticle, err error) {
	buf := make([]*model.BlogArticle, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b blogArticleDo) FindInBatches(result *[]*model.BlogArticle, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b blogArticleDo) Attrs(attrs ...field.AssignExpr) *blogArticleDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b blogArticleDo) Assign(attrs ...field.AssignExpr) *blogArticleDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b blogArticleDo) Joins(fields ...field.RelationField) *blogArticleDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b blogArticleDo) Preload(fields ...field.RelationField) *blogArticleDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b blogArticleDo) FirstOrInit() (*model.BlogArticle, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticle), nil
	}
}

func (b blogArticleDo) FirstOrCreate() (*model.BlogArticle, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogArticle), nil
	}
}

func (b blogArticleDo) FindByPage(offset int, limit int) (result []*model.BlogArticle, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b blogArticleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b blogArticleDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b blogArticleDo) Delete(models ...*model.BlogArticle) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *blogArticleDo) withDO(do gen.Dao) *blogArticleDo {
	b.DO = *do.(*gen.DO)
	return b
}
