// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/JunLang-7/blog-service/internal/model"
)

func newBlogTag(db *gorm.DB, opts ...gen.DOOption) blogTag {
	_blogTag := blogTag{}

	_blogTag.blogTagDo.UseDB(db, opts...)
	_blogTag.blogTagDo.UseModel(&model.BlogTag{})

	tableName := _blogTag.blogTagDo.TableName()
	_blogTag.ALL = field.NewAsterisk(tableName)
	_blogTag.ID = field.NewUint32(tableName, "id")
	_blogTag.Name = field.NewString(tableName, "name")
	_blogTag.CreatedOn = field.NewUint32(tableName, "created_on")
	_blogTag.CreatedBy = field.NewString(tableName, "created_by")
	_blogTag.ModifiedOn = field.NewUint32(tableName, "modified_on")
	_blogTag.ModifiedBy = field.NewString(tableName, "modified_by")
	_blogTag.DeletedOn = field.NewUint32(tableName, "deleted_on")
	_blogTag.IsDel = field.NewUint32(tableName, "is_del")
	_blogTag.State = field.NewUint32(tableName, "state")

	_blogTag.fillFieldMap()

	return _blogTag
}

// blogTag 标签管理
type blogTag struct {
	blogTagDo blogTagDo

	ALL        field.Asterisk
	ID         field.Uint32
	Name       field.String // 标签名称
	CreatedOn  field.Uint32 // 创建时间
	CreatedBy  field.String // 创建人
	ModifiedOn field.Uint32 // 修改时间
	ModifiedBy field.String // 修改人
	DeletedOn  field.Uint32 // 删除时间
	IsDel      field.Uint32 // 是否删除 0 为未删除、1 为已删除
	State      field.Uint32 // 状态 0 为禁用、1 为启用

	fieldMap map[string]field.Expr
}

func (b blogTag) Table(newTableName string) *blogTag {
	b.blogTagDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b blogTag) As(alias string) *blogTag {
	b.blogTagDo.DO = *(b.blogTagDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *blogTag) updateTableName(table string) *blogTag {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewUint32(table, "id")
	b.Name = field.NewString(table, "name")
	b.CreatedOn = field.NewUint32(table, "created_on")
	b.CreatedBy = field.NewString(table, "created_by")
	b.ModifiedOn = field.NewUint32(table, "modified_on")
	b.ModifiedBy = field.NewString(table, "modified_by")
	b.DeletedOn = field.NewUint32(table, "deleted_on")
	b.IsDel = field.NewUint32(table, "is_del")
	b.State = field.NewUint32(table, "state")

	b.fillFieldMap()

	return b
}

func (b *blogTag) WithContext(ctx context.Context) *blogTagDo { return b.blogTagDo.WithContext(ctx) }

func (b blogTag) TableName() string { return b.blogTagDo.TableName() }

func (b blogTag) Alias() string { return b.blogTagDo.Alias() }

func (b blogTag) Columns(cols ...field.Expr) gen.Columns { return b.blogTagDo.Columns(cols...) }

func (b *blogTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *blogTag) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 9)
	b.fieldMap["id"] = b.ID
	b.fieldMap["name"] = b.Name
	b.fieldMap["created_on"] = b.CreatedOn
	b.fieldMap["created_by"] = b.CreatedBy
	b.fieldMap["modified_on"] = b.ModifiedOn
	b.fieldMap["modified_by"] = b.ModifiedBy
	b.fieldMap["deleted_on"] = b.DeletedOn
	b.fieldMap["is_del"] = b.IsDel
	b.fieldMap["state"] = b.State
}

func (b blogTag) clone(db *gorm.DB) blogTag {
	b.blogTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b blogTag) replaceDB(db *gorm.DB) blogTag {
	b.blogTagDo.ReplaceDB(db)
	return b
}

type blogTagDo struct{ gen.DO }

func (b blogTagDo) Debug() *blogTagDo {
	return b.withDO(b.DO.Debug())
}

func (b blogTagDo) WithContext(ctx context.Context) *blogTagDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b blogTagDo) ReadDB() *blogTagDo {
	return b.Clauses(dbresolver.Read)
}

func (b blogTagDo) WriteDB() *blogTagDo {
	return b.Clauses(dbresolver.Write)
}

func (b blogTagDo) Session(config *gorm.Session) *blogTagDo {
	return b.withDO(b.DO.Session(config))
}

func (b blogTagDo) Clauses(conds ...clause.Expression) *blogTagDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b blogTagDo) Returning(value interface{}, columns ...string) *blogTagDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b blogTagDo) Not(conds ...gen.Condition) *blogTagDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b blogTagDo) Or(conds ...gen.Condition) *blogTagDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b blogTagDo) Select(conds ...field.Expr) *blogTagDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b blogTagDo) Where(conds ...gen.Condition) *blogTagDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b blogTagDo) Order(conds ...field.Expr) *blogTagDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b blogTagDo) Distinct(cols ...field.Expr) *blogTagDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b blogTagDo) Omit(cols ...field.Expr) *blogTagDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b blogTagDo) Join(table schema.Tabler, on ...field.Expr) *blogTagDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b blogTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *blogTagDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b blogTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *blogTagDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b blogTagDo) Group(cols ...field.Expr) *blogTagDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b blogTagDo) Having(conds ...gen.Condition) *blogTagDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b blogTagDo) Limit(limit int) *blogTagDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b blogTagDo) Offset(offset int) *blogTagDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b blogTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *blogTagDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b blogTagDo) Unscoped() *blogTagDo {
	return b.withDO(b.DO.Unscoped())
}

func (b blogTagDo) Create(values ...*model.BlogTag) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b blogTagDo) CreateInBatches(values []*model.BlogTag, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b blogTagDo) Save(values ...*model.BlogTag) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b blogTagDo) First() (*model.BlogTag, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogTag), nil
	}
}

func (b blogTagDo) Take() (*model.BlogTag, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogTag), nil
	}
}

func (b blogTagDo) Last() (*model.BlogTag, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogTag), nil
	}
}

func (b blogTagDo) Find() ([]*model.BlogTag, error) {
	result, err := b.DO.Find()
	return result.([]*model.BlogTag), err
}

func (b blogTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BlogTag, err error) {
	buf := make([]*model.BlogTag, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b blogTagDo) FindInBatches(result *[]*model.BlogTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b blogTagDo) Attrs(attrs ...field.AssignExpr) *blogTagDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b blogTagDo) Assign(attrs ...field.AssignExpr) *blogTagDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b blogTagDo) Joins(fields ...field.RelationField) *blogTagDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b blogTagDo) Preload(fields ...field.RelationField) *blogTagDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b blogTagDo) FirstOrInit() (*model.BlogTag, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogTag), nil
	}
}

func (b blogTagDo) FirstOrCreate() (*model.BlogTag, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlogTag), nil
	}
}

func (b blogTagDo) FindByPage(offset int, limit int) (result []*model.BlogTag, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b blogTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b blogTagDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b blogTagDo) Delete(models ...*model.BlogTag) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *blogTagDo) withDO(do gen.Dao) *blogTagDo {
	b.DO = *do.(*gen.DO)
	return b
}
